### ISSUE TITLE
Prevent submodules fetching

### ISSUE THREAD

**Issue by dvic** [depot/build-push-action#36]
Is there a way to prevent the action from fetching submodules? The github oidc token does not have access to it so the build is failing.

**Comment by jacobwgillespie** [comment]
Hey, yeah the default is to fetch context from git, but if you can specify to transfer context from the filesystem instead:

```yaml
- uses: depot/build-push-action@v1
  with:
    context: .
```
